global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "nodes"
    static_configs:
      - targets:
          - "node-exporter-node1:9100"
          - "node-exporter-node2:9100"
          - "node-exporter-node3:9100"

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
